version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: tutorials_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    container_name: redisdb
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis-testpassword"]
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data:
